---
AWSTemplateFormatVersion: '2010-09-09'
Description: CF template for creating elphant project
Parameters:
  KeyName:
    Description: Key Pair name
    Type: AWS::EC2::KeyPair::KeyName
    Default: my-key
Resources:
  SecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: My security group
      VpcId: vpc-a20933da
      SecurityGroupIngress:
        - IpProtocol: "tcp"
          FromPort: "22"
          ToPort: "22"
          CidrIp: "0.0.0.0/0"
        - IpProtocol: "tcp"
          FromPort: "3000"
          ToPort: "3000"
          CidrIp: "0.0.0.0/0"
        - IpProtocol: "tcp"
          FromPort: "21"
          ToPort: "21"
          CidrIp: "0.0.0.0/0"
  Server:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-005daf69
      KeyName:
        Ref: KeyName
      SecurityGroupIds:
      - Ref: SecurityGroup
      SubnetId: subnet-b9d0f1f2
Outputs:
  PublicName:
    Value:
      Fn::GetAtt:
      - Server
      - PublicDnsName
    Description: Public name (connect via SSH)
